FreelancerSystem/Controllers/ClientController.cs
using FreelancerSystem.Models;
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.Owin;
using Microsoft.AspNetCore.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace FreelancerSystem.Controllers
{
    public class ClientController : Controller
    {
        //here i create instance of database that name is ApplicationDbContext
        ApplicationDbContext db;
        public ClientController()
        {
            db = new ApplicationDbContext();
        }
        // GET: Client
        public ActionResult Index()
        {
            return View();
        }

        // GET: Client/Details/5
        //here i get the client information 
        public ActionResult ClientInformation()
        {
            //here i get the cureent user id 
            string currentUserId = User.Identity.GetUserId();
            ApplicationUser currentUser = db.Users.FirstOrDefault(x => x.Id == currentUserId);

            //here i find the data of user by using id
            return View(currentUser);
        }
        public FileContentResult UserPhoto()
        {
            string userId = User.Identity.GetUserId();
            var dbUsers = HttpContext.GetOwinContext().Get<ApplicationDbContext>();
            var userImage = dbUsers.Users.Where(x => x.Id == userId).FirstOrDefault();
            return new FileContentResult(userImage.UserPhoto, "image/jpeg");
        }

        public ActionResult ChangePassword()
        {
            return View();
        }
           
         // GET: Client/CreatePost
        public ActionResult CreatePost()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult CreatePost(Post post)
        {
            if (ModelState.IsValid)
            {
                post.Creation_Date = DateTime.Now;
                post.ClientId = User.Identity.GetUserId();
                post.ClientName = User.Identity.GetUserName();
                post.postId = Guid.NewGuid().ToString();
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("GetAllPost");
            }

            return View(post);
        }
        //here history posts that create by client
        //here it is delete post [Get] request
        public ActionResult DeletePost(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
        [HttpPost, ActionName("DeletePost")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmedPost(string id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("GetAllPost");
        }

        public ActionResult EditPost(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }
        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult EditPost(Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }

        public ActionResult GetAllPost()
        {
            string currentId = User.Identity.GetUserId();
            var result = db.Posts.Where(x => x.ClientId == currentId);
            var userPosts = result.ToList();
            return View(userPosts);
        }
        //here i edit the post
      
        // POST: Client/Create


        // GET: Client/Edit/5
        public ActionResult EditInfo(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            string currentUser = User.Identity.GetUserId();
            ApplicationUser applicationUser = db.Users.Find(currentUser);
            if (applicationUser == null)
            {
                return HttpNotFound();
            }
            return View(applicationUser);
        }

        // POST: Client/Edit/5
        [HttpPost]
        public ActionResult EditInfo( ApplicationUser applicationUser)
        {
            if (ModelState.IsValid)
            {
                db.Entry(applicationUser).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("ClientInformation");
            }
            
            return View(applicationUser);
            
        }
        //here i delete the post
        // GET: Client/Delete/5
        
        // POST: Client/Delete/5
        
        
    }
}

FreelancerSystem/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using FreelancerSystem.Models;
using Microsoft.AspNet.Identity;

namespace FreelancerSystem.Controllers
{
    public class PostsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        
        // GET: Posts
        public ActionResult Index()
        {
            
            return View(db.Posts.ToList());
        }

        // GET: Posts/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // GET: Posts/Create
        public ActionResult Create()
        {
            
            return View();
        }

        // POST: Posts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create( Post post)
        {
            if (ModelState.IsValid)
            {
                post.Creation_Date = DateTime.Now;
                post.ClientId=User.Identity.GetUserId();
                post.ClientName = User.Identity.GetUserName();
                post.postId = Guid.NewGuid().ToString();
                db.Posts.Add(post);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            
            return View(post);
        }
        
        // GET: Posts/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "postId,ClientId,Title,JopType,JobBudget,Creation_Date,NumProposal,IsAprroved,postDescription")] Post post)
        {
            if (ModelState.IsValid)
            {
                db.Entry(post).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(post);
        }
        
        // GET: Posts/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Post post = db.Posts.Find(id);
            if (post == null)
            {
                return HttpNotFound();
            }
            return View(post);
        }

        // POST: Posts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            Post post = db.Posts.Find(id);
            db.Posts.Remove(post);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

FreelancerSystem/Views/Shared/_DashBoardLayout.cshtml
<!DOCTYPE html>
@RenderSection("scripts", required: false)
<html>
<head>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Font Awesome JS -->
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/DashBoardLayout.css" />
    <link rel="stylesheet" href="~/Content/fontawesome.css" />
    <script src="~/Content/solid.min.js"></script>
    <script src="~/Content/jQuery.js"></script>
    <script src="~/Content/fontawesome.js"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });


    </script>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <style>
        a {
            text-decoration: none
        }

            a:hover {
                text-decoration: none
            }

        .wrapper.sidebar {
        }

        #sidebar ul li.active > a {
            background-color: #16c0f2;
        }

        .sidebar {
            background-color: aqua;
        }

        #sidebar .sidebar-header {
            background-color: #16c0f2;
            border-radius: 10px;
        }

        .list-unstyled {
            background-color: #5BC0DE;
        }

        #sidebar {
            background-color: #5BC0DE;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <!--<nav id="sidebar">
            <div class="sidebar-header">
                <h4>Freelancer Dashboard</h4>
            </div>-->
        <!--</nav>-->
        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                @Html.ActionLink("Profile", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Users Pages", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Post Page", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Post Requests", "Index", "Home")
                            </li>
                            

                        </ul>

                        @Html.Partial("_LoginPartial")


                    </div>

                </div>
            </nav>
            <div class="container" style="width:80%">
                @RenderBody()
            </div>
        </div>

    </div>

</body>

</html>

FreelancerSystem/Views/Shared/_FactoryLayout.cshtml
<!DOCTYPE html>
@RenderSection("scripts", required: false)
<html>
<head>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Font Awesome JS -->
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/DashBoardLayout.css" />
    <link rel="stylesheet" href="~/Content/fontawesome.css" />
    <script src="~/Content/solid.min.js"></script>
    <script src="~/Content/jQuery.js"></script>
    <script src="~/Content/fontawesome.js"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });
       
    
    </script>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <style>
        a{
            text-decoration:none
        }
        a:hover{
            text-decoration:none
        }
        .wrapper.sidebar{
            
        }
        #sidebar ul li.active > a {
            background-color: #16c0f2;
        }
        .sidebar {
            background-color: aqua;
        }
        #sidebar .sidebar-header {
            background-color: #16c0f2;
            border-radius:10px;
        }
        .list-unstyled {
            background-color: #5BC0DE;
        }
        #sidebar {
            background-color: #5BC0DE;
        }
        
    </style>
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h4>Freelancer Dashboard</h4>
            </div>

            <ul class="list-unstyled components">
                
                <li>
                    @Html.ActionLink("Profile", "ClientInformation", "Client")
                </li>
                <li>
                    @Html.ActionLink("posts","createPost","Client")
                </li>
                <li>
                    @Html.ActionLink("My Posts", "ClientInformation", "Client")
                </li>
                <li>
                    @Html.ActionLink("Recived Proposals", "ClientInformation", "Client")
                </li>
                <li>
                    @Html.ActionLink("Home", "ClientInformation", "Client")
                </li>
            </ul>

            
        </nav>

        <!-- Page Content  -->
        <div id="content">
           
            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">

                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                        <span>Toggle Sidebar</span>
                    </button>
                    
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <ul class="nav navbar-nav ml-auto">
                            <li class="nav-item active">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>

                        </ul>
                        @Html.Partial("_LoginPartial");
                    </div>

                </div>
            </nav>
            <div>
                @RenderBody()
            </div>
        </div>

    </div>

</body>

</html>

FreelancerSystem/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Freelance System", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                   

                    @if (User.Identity.IsAuthenticated)
                    {
                        if (User.IsInRole("Admins"))
                        {
                            <li>@Html.ActionLink("Create", "Create", "Posts")</li>

                        }
                    }

                </ul>

                @Html.Partial("_LoginPartial")
                @if (!User.Identity.IsAuthenticated)
                {
                    
                    <form class="form-inline my-2 my-lg-0 " style="margin:10px;">
                        <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                        <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form> 
                }
                
            </div>
        </div>
    </div>
    <div class="container ">
        <div class="row">
             @RenderBody()
        </div>
       
        
        <div class="row">
            <footer>
                <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
            </footer>
        </div>
        
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

FreelancerSystem/Views/Shared/_WallLayout.cshtml
<!DOCTYPE html>
@RenderSection("scripts", required: false)
<html>
<head>
    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">

    <!-- Font Awesome JS -->
    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="~/Content/DashBoardLayout.css" />
    <link rel="stylesheet" href="~/Content/fontawesome.css" />
    <script src="~/Content/solid.min.js"></script>
    <script src="~/Content/jQuery.js"></script>
    <script src="~/Content/fontawesome.js"></script>
    <script>
        $(document).ready(function () {
            $('#sidebarCollapse').on('click', function () {
                $('#sidebar').toggleClass('active');
            });
        });


    </script>
    <link rel="stylesheet" href="~/Content/bootstrap.min.css" />
    <style>
        a {
            text-decoration: none
        }

            a:hover {
                text-decoration: none
            }

        .wrapper.sidebar {
        }

        #sidebar ul li.active > a {
            background-color: #16c0f2;
        }

        .sidebar {
            background-color: aqua;
        }

        #sidebar .sidebar-header {
            background-color: #16c0f2;
            border-radius: 10px;
        }

        .list-unstyled {
            background-color: #5BC0DE;
        }

        #sidebar {
            background-color: #5BC0DE;
        }
    </style>
</head>
<body>
    <div class="wrapper">
        <!-- Sidebar  -->
        <!--<nav id="sidebar">
            <div class="sidebar-header">
                <h4>Freelancer Dashboard</h4>
            </div>-->



        <!--</nav>-->

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>

                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        
                        <ul class="nav navbar-nav ml-auto">
                           
                            <li class="nav-item active">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                @Html.ActionLink("Home", "Index", "Home")
                            </li>
                            <li class="nav-item">
                                <form class="form-inline" style="margin:10px;">
                                    <input class="form-control mr-sm-2" type="search" placeholder="Search" style="width:300px" aria-label="Search">
                                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                                </form>
                            </li>

                        </ul>

                        @Html.Partial("_LoginPartial")
                        
                    
                    </div>

                </div>
            </nav>
            <div class="container" style="width:80%">
                @RenderBody()
            </div>
        </div>

    </div>

</body>

</html>